keywords = ["Production Engineer", "Quality Engineer", "Manufacturing Engineer", "Graduate Engineer Trainee", "GET Mechanical", "Operations Engineer", "Supply Chain Engineer", "Supply Chain Analyst", "Logistics Engineer", "Procurement Engineer", "Industrial Engineer", "Process Engineer", "Plant Engineer", "Operations Analyst"]
search_location = "India"
sort_by = "Most recent"
date_posted = "Any time"
experience_level = ["Internship", "Entry level"]
job_type = ["Full-time", "Contract"]
on_site = ["On-site", "Hybrid", "Remote"]
easy_apply_only = True
apply_once_at_a_company = False
security_clearance = False
did_masters = False
search_blacklist = []
company_blacklist = []
blacklist_keywords = []
